import {
  getAvailableLocales,
  setDefaultLocale,
  setStrings,
} from './lib/functions';
import {
  extend,
  interpolate,
  localize,
  parseDate,
  pluralize,
  toCurrency,
  toHumanSize,
  toNumber,
  toPercentage,
  toTime,
  translate,
} from './lib/i18n';
import {
  getCalendar,
  getCountry,
  getCurrencies,
  getLocales,
  getNumberFormatSettings,
  getTemperatureUnit,
  getTimeZone,
  uses24HourClock,
  usesMetricSystem,
  usesAutoDateAndTime,
  usesAutoTimeZone,
  addEventListener,
  removeEventListener,
  findBestAvailableLanguage,
} from 'react-native-localize';

const reactNativeI18nStringsPackage = {
  addEventListener,
  findBestAvailableLanguage,
  getAvailableLocales,
  getCalendar,
  getCountry,
  getCurrencies,
  getLocales,
  getNumberFormatSettings,
  getTemperatureUnit,
  getTimeZone,
  interpolate,
  localize,
  parseDate,
  pluralize,
  removeEventListener,
  setDefaultLocale,
  setStrings,
  toCurrency,
  toHumanSize,
  toNumber,
  toPercentage,
  toTime,
  translate,
  uses24HourClock,
  usesAutoDateAndTime,
  usesAutoTimeZone,
  usesMetricSystem,
};

export {
  addEventListener,
  findBestAvailableLanguage,
  getAvailableLocales,
  getCalendar,
  getCountry,
  getCurrencies,
  getLocales,
  getNumberFormatSettings,
  getTemperatureUnit,
  getTimeZone,
  interpolate,
  localize,
  parseDate,
  pluralize,
  removeEventListener,
  setDefaultLocale,
  setStrings,
  toCurrency,
  toHumanSize,
  toNumber,
  toPercentage,
  toTime,
  translate,
  uses24HourClock,
  usesAutoDateAndTime,
  usesAutoTimeZone,
  usesMetricSystem,
};
export default reactNativeI18nStringsPackage;
