# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'I18nStrings' do
  # Pods for I18nStrings
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
end
